CREATE TABLE asset_history (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    asset_id INTEGER NOT NULL REFERENCES asset(id) ON DELETE CASCADE,
old_status VARCHAR(20)
    CHECK (old_status IN ('IN_TRANSIT','CONFIGURING','IN_STOCK','IN_USE','RESERVED','UNDER_REPAIR','IN_WARRANTY',          'STOLEN_LOST','DISPOSED')),
new_status VARCHAR(20) NOT NULL
    CHECK (new_status IN ('IN_TRANSIT','CONFIGURING','IN_STOCK','IN_USE','RESERVED','UNDER_REPAIR','IN_WARRANTY',  'STOLEN_LOST','DISPOSED')),

    old_user_id INTEGER REFERENCES site_user(id),
    new_user_id INTEGER REFERENCES site_user(id),

    old_site_id INTEGER REFERENCES site(id),
    new_site_id INTEGER REFERENCES site(id),
    
    moved_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);